DROP VIEW IF EXISTS vw_customer_cohort;
CREATE VIEW vw_customer_cohort AS SELECT a.account_id,date(a.created_at,'start of month') cohort_month,a.created_at signup_date,a.acquisition_channel,a.region,a.segment,p.plan_name,p.monthly_price,s.subscription_id,date(s.started_at) subscription_start,date(s.ended_at) churn_date,s.status,s.mrr FROM accounts a JOIN subscriptions s ON a.account_id=s.account_id JOIN plans p ON s.plan_id=p.plan_id;

DROP VIEW IF EXISTS vw_cohort_retention;
CREATE VIEW vw_cohort_retention AS WITH cohort_sizes AS (SELECT cohort_month,COUNT(DISTINCT account_id) cohort_size FROM customer_monthly_activity WHERE months_since_cohort=0 GROUP BY cohort_month), retained AS (SELECT cohort_month,months_since_cohort,COUNT(DISTINCT account_id) retained_customers FROM customer_monthly_activity WHERE months_since_cohort BETWEEN 0 AND 12 GROUP BY cohort_month,months_since_cohort) SELECT r.cohort_month,r.months_since_cohort,c.cohort_size,r.retained_customers,ROUND(1.0*r.retained_customers/c.cohort_size,4) retention_rate FROM retained r JOIN cohort_sizes c USING(cohort_month);

DROP VIEW IF EXISTS vw_channel_m6_retention;
CREATE VIEW vw_channel_m6_retention AS WITH mature AS (SELECT DISTINCT cohort_month FROM customer_monthly_activity WHERE date(cohort_month,'+6 months')<='2025-12-01'), base AS (SELECT DISTINCT a.account_id,a.acquisition_channel,date(a.created_at,'start of month') cohort_month FROM accounts a JOIN mature m ON date(a.created_at,'start of month')=m.cohort_month),m6 AS (SELECT DISTINCT account_id FROM customer_monthly_activity WHERE months_since_cohort=6) SELECT b.acquisition_channel,COUNT(*) cohort_customers,SUM(CASE WHEN m.account_id IS NOT NULL THEN 1 ELSE 0 END) retained_m6,ROUND(1.0*SUM(CASE WHEN m.account_id IS NOT NULL THEN 1 ELSE 0 END)/COUNT(*),4) m6_retention FROM base b LEFT JOIN m6 m USING(account_id) GROUP BY b.acquisition_channel;

DROP VIEW IF EXISTS vw_plan_m6_retention;
CREATE VIEW vw_plan_m6_retention AS WITH mature AS (SELECT DISTINCT cohort_month FROM customer_monthly_activity WHERE date(cohort_month,'+6 months')<='2025-12-01'), base AS (SELECT DISTINCT a.account_id,p.plan_name,date(a.created_at,'start of month') cohort_month FROM accounts a JOIN subscriptions s ON a.account_id=s.account_id JOIN plans p ON s.plan_id=p.plan_id JOIN mature m ON date(a.created_at,'start of month')=m.cohort_month),m6 AS (SELECT DISTINCT account_id FROM customer_monthly_activity WHERE months_since_cohort=6) SELECT b.plan_name,COUNT(*) cohort_customers,SUM(CASE WHEN m.account_id IS NOT NULL THEN 1 ELSE 0 END) retained_m6,ROUND(1.0*SUM(CASE WHEN m.account_id IS NOT NULL THEN 1 ELSE 0 END)/COUNT(*),4) m6_retention FROM base b LEFT JOIN m6 m USING(account_id) GROUP BY b.plan_name;
